build:
  os: ubuntu-24.04
  tools:
    python: '3.11'
python:
  install:
  - requirements: docs/requirements.txt
  - requirements: requirements.txt
sphinx:
  configuration: docs/source/conf.py
version: 2
